dist: trusty
language: node_js

node_js:
  - '9.2.0'

before_script:
  - npm install
  - npm uninstall fibers
  - npm install fibers
  - npm update

script:
- npm run suite All

sudo: false
addons:
  chrome: stable
